# Generated by Django 4.0.6 on 2022-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nivel',
            field=models.CharField(default='kinder', max_length=20),
        ),
    ]
