# Generated by Django 4.0.6 on 2022-07-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
