# Generated by Django 4.0.6 on 2022-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email_responsable',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='telefono_responsable',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
