# Generated by Django 4.0.6 on 2025-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_responsable_book_alumno_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nivel',
            field=models.CharField(choices=[('maternal', 'Materna'), ('kinder', 'Kinder'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria')], default='kinder', max_length=20),
        ),
    ]
